-- Each new term in the Fibonacci sequence is generated by adding the previous
-- two terms.  By starting with 1 and 2, the first 10 terms will be:
-- 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
--
-- By considering the terms in the Fibonacci sequence whose values do not
-- exceed four million, find the sum of the even-valued terms.

-- Generate the n-th Fibonacci number (very slowly for large n's)
fib :: Num a => a -> a
fib 0 = 1
fib 1 = 2
fib n = fib (n-2) + fib (n-1)

-- Produces the infinite Fibonacci sequence
fibonacci :: Num a => [a]
fibonacci = fibs [1, 2]
      where fibs (a:b:[]) = a:(fibs [b, a+b])

main = do
    let answer = sum $ filter even $ takeWhile (<4000000) fibonacci
    putStrLn $ "The sum of the even Fibonacci values less than 4 million is " ++ show answer
